esphome:
  name: sml

esp8266:
  board: nodemcuv2

# Enable logging
logger: 
  baud_rate: 0  

# Enable Home Assistant API
api:
  encryption:
    key: "###" #Key Einsetzen

ota:
  password: "53509132a9fbaba8b2a6e5589853e857"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
        # Set this to the IP of the ESP
    #static_ip: 192.168.1.83
                # Set this to the IP address of the router. Often ends with .1
    #gateway: 192.168.1.1
                        # The subnet of the network. 255.255.255.0 works for most home networks.
    #subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "####"
    password: "###"

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

external_components:
  - source:
      type: git
      url: https://github.com/alengwenus/esphome_components
    components: [ sml ]
                        

                                        
sensor:
  - platform: sml
    name: "Strom aus dem Netz"
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 5
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
      - throttle: 10s
                                                                                        
  - platform: sml
    name: "Strom eingespeist" 
    obis_code: "1-0:2.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 5
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
      - throttle: 5s 

  - platform: sml
    name: "Aktuele Bezugsleistun"
    obis_code: "1-0:16.7.0*255"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing

